mrr/dashboard/urls.py
from django.urls import path

from . import views

app_name="dashboard"

urlpatterns = [
    path("", views.index, name="index"),
]

mrr/mrr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dashboard.urls")),
]

mrr/dashboard/models.py
from django.db import models, connection

from datetime import date
from datetime import datetime

from .graficos import get_gauge
from .graficos import get_pie
from .graficos import get_bar
from .graficos import get_line

import pandas as pd
import plotly.express as px

class ControleVersao(models.Model):
    cd_versao = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    dt_versao = models.DateField(default=date.today)
    fato_versao = models.IntegerField(default=1, unique=True)

class DimSegmento(models.Model):
    cd_segmento = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    nm_segmento = models.CharField(max_length=75, unique=True)

class DimCliente(models.Model):
    cd_cliente = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    nr_cliente = models.IntegerField()
    nm_cliente = models.CharField(max_length=100)

    class Meta:
        unique_together = ("nr_cliente", "nm_cliente")

class DimLocalidade(models.Model):
    cd_localidade = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    nm_cidade = models.CharField(max_length=75)
    nm_estado = models.CharField(max_length=75)

    class Meta:
        unique_together = ("nm_cidade", "nm_estado")

class DimPlano(models.Model):
    cd_plano = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    nm_plano = models.CharField(max_length=75, unique=True)

class DimDia(models.Model):
    cd_dia = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    dia = models.IntegerField(unique=True)

class DimMes(models.Model):
    cd_mes = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    nr_mes = models.IntegerField(unique=True)
    nm_nr_mes = models.CharField(max_length=2, blank=True, null=True)
    nm_mes = models.CharField(max_length=10, unique=True)
    sg_mes = models.CharField(max_length=3, unique=True)

class DimAno(models.Model):
    cd_ano = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    ano = models.IntegerField(unique=True)

class FatoMrr(models.Model):
    cd_fato_mrr = models.AutoField(primary_key=True, serialize=True, auto_created=True)
    cd_cliente = models.ForeignKey(DimCliente, on_delete=models.PROTECT)
    cd_localidade = models.ForeignKey(DimLocalidade, on_delete=models.PROTECT)
    cd_plano = models.ForeignKey(DimPlano, on_delete=models.PROTECT)
    cd_dia = models.ForeignKey(DimDia, on_delete=models.PROTECT)
    cd_mes = models.ForeignKey(DimMes, on_delete=models.PROTECT)
    cd_ano = models.ForeignKey(DimAno, on_delete=models.PROTECT)
    periodicidade = models.IntegerField(default=1)
    vl_mrr = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    vl_cancelamento = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    vl_expansao = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    sn_novo = models.BooleanField(default=False)
    sn_cancelado = models.BooleanField(default=False)
    sn_renascido = models.BooleanField(default=False)

    @staticmethod
    def mrr(dt_inicio, dt_fim=str(date.today())):

        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        mes_fim = datetime.strptime(dt_fim, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 
        ano_fim = datetime.strptime(dt_fim, "%Y-%m-%d").year

        query = f"""SELECT sum(vl_mrr) as total FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimmes b ON a.cd_mes_id = b.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND b.nr_mes >= {mes_inicio}
        AND b.nr_mes <= {mes_fim}
        AND c.ano >= {ano_inicio}
        AND c.ano <= {ano_fim}
        AND sn_cancelado = {False}
        """
        df = pd.read_sql(query, connection)
        get_gauge(df.iloc[0]["total"], "Receita Mensal","mrr")

    @staticmethod
    def new_mrr(dt_inicio, dt_fim=str(date.today())):

        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        mes_fim = datetime.strptime(dt_fim, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 
        ano_fim = datetime.strptime(dt_fim, "%Y-%m-%d").year

        query = f"""SELECT sum(vl_mrr) as total FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimmes b ON a.cd_mes_id = b.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND b.nr_mes >= {mes_inicio}
        AND b.nr_mes <= {mes_fim}
        AND c.ano >= {ano_inicio}
        AND c.ano <= {ano_fim}
        AND sn_cancelado = {False}
        AND sn_novo = {True}
        """
        df = pd.read_sql(query, connection)
        get_gauge(df.iloc[0]["total"], "Nova Receita","new_mrr")

    @staticmethod
    def expansion_mrr(dt_inicio, dt_fim=str(date.today())):
        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        mes_fim = datetime.strptime(dt_fim, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 
        ano_fim = datetime.strptime(dt_fim, "%Y-%m-%d").year

        query = f"""SELECT sum(vl_expansao) as total FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimmes b ON a.cd_mes_id = b.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND b.nr_mes >= {mes_inicio}
        AND b.nr_mes <= {mes_fim}
        AND c.ano >= {ano_inicio}
        AND c.ano <= {ano_fim}
        AND sn_cancelado = {False}
        AND vl_expansao >= 0
        """
        df = pd.read_sql(query, connection)
        get_gauge(df.iloc[0]["total"], "Receita em expansão","expansion_mrr")
    
    @staticmethod
    def contraction_mrr(dt_inicio, dt_fim=str(date.today())):
        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        mes_fim = datetime.strptime(dt_fim, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 
        ano_fim = datetime.strptime(dt_fim, "%Y-%m-%d").year

        query = f"""SELECT sum(vl_expansao) as total FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimmes b ON a.cd_mes_id = b.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND b.nr_mes >= {mes_inicio}
        AND b.nr_mes <= {mes_fim}
        AND c.ano >= {ano_inicio}
        AND c.ano <= {ano_fim}
        AND sn_cancelado = {False}
        AND vl_expansao <= 0
        """
        df = pd.read_sql(query, connection)
        get_gauge(df.iloc[0]["total"], "Receita em contração","contraction_mrr")
    
    @staticmethod
    def canceled_mrr(dt_inicio, dt_fim=str(date.today())):
        
        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        mes_fim = datetime.strptime(dt_fim, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 
        ano_fim = datetime.strptime(dt_fim, "%Y-%m-%d").year

        query = f"""SELECT sum(vl_mrr) as total FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimmes b ON a.cd_mes_id = b.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND b.nr_mes >= {mes_inicio}
        AND b.nr_mes <= {mes_fim}
        AND c.ano >= {ano_inicio}
        AND c.ano <= {ano_fim}
        AND sn_cancelado = {True}
        """
        df = pd.read_sql(query, connection)
        get_gauge(df.iloc[0]["total"], "Receita cancelada","canceled_mrr")


    @staticmethod
    def ressurected_mrr(dt_inicio, dt_fim=str(date.today())):
        
        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        mes_fim = datetime.strptime(dt_fim, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 
        ano_fim = datetime.strptime(dt_fim, "%Y-%m-%d").year

        query = f"""SELECT sum(vl_mrr) as total FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimmes b ON a.cd_mes_id = b.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND b.nr_mes >= {mes_inicio}
        AND b.nr_mes <= {mes_fim}
        AND c.ano >= {ano_inicio}
        AND c.ano <= {ano_fim}
        AND sn_renascido = {True}
        """
        df = pd.read_sql(query, connection)
        get_gauge(df.iloc[0]["total"], "Receita de retorno","ressurected_mrr")


    @staticmethod
    def tendencia_mrr(dt_inicio, dt_fim=str(date.today())):
        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 

        query = f"""SELECT sum(vl_mrr) as total, TO_DATE(CONCAT(b.nm_nr_mes, c.ano), 'MMYYYY') as periodo FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimmes b ON a.cd_mes_id = b.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND b.nr_mes >= {mes_inicio}
        AND c.ano >= {ano_inicio}
        AND sn_cancelado = {False}
        GROUP BY periodo
        ORDER BY periodo
        """
        df = pd.read_sql(query, connection)
        df["periodo"] = pd.to_datetime(df["periodo"])
        
        get_line(df, "periodo", "total", "tendencia_mrr", "Variação de Receita por Período")
        #get_gauge(df["total"].iloc[0], "Receita cancelada","canceled_mrr")
    
    @staticmethod
    def localidade_valor(dt_inicio, dt_fim=str(date.today())):

        mes_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").month
        mes_fim = datetime.strptime(dt_fim, "%Y-%m-%d").month
        ano_inicio = datetime.strptime(dt_inicio, "%Y-%m-%d").year 
        ano_fim = datetime.strptime(dt_fim, "%Y-%m-%d").year

        query = f""" SELECT sum(a.vl_mrr) as Receita, b.nm_estado as Estado
        FROM dashboard_fatomrr a
        INNER JOIN dashboard_dimlocalidade b ON a.cd_localidade_id = b.cd_localidade
        INNER JOIN dashboard_dimmes d ON a.cd_mes_id = d.cd_mes
        INNER JOIN dashboard_dimano c ON a.cd_ano_id = c.cd_ano
        AND d.nr_mes >= {mes_inicio}
        AND d.nr_mes <= {mes_fim}
        AND c.ano >= {ano_inicio}
        AND c.ano <= {ano_fim}
        GROUP BY b.nm_estado

mrr/dashboard/forms.py
from django import forms


class PeriodoForm(forms.Form):
    dt_inicio = forms.DateField(label="Início")
    dt_fim = forms.DateField(label="Fim")

mrr/dashboard/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render

import datetime
# Create your views here.

from .forms import PeriodoForm

from .models import FatoMrr


def index(request):

    context = {}

    if request.method == "GET":
        dt_fim = datetime.date.today()
        primeiro = dt_fim.replace(day=1)
        dt_inicio = str(primeiro - datetime.timedelta(days=1825))

        FatoMrr.get_dashboard(dt_inicio)        

    elif request.method == "POST":
        form = PeriodoForm(request.POST)
        if form.is_valid():
            dt_inicio = form.cleaned_data["dt_inicio"]
            dt_fim = form.cleaned_data["dt_fim"]
            FatoMrr.get_dashboard(str(dt_inicio), str(dt_fim))
    else:
        return HttpResponseNotAllowed(['GET', 'POST'])
    
    form = PeriodoForm(initial={
        "dt_inicio":str(dt_inicio),
        "dt_fim":str(dt_fim)
    })
    context["form"] = form

    return render(request, "dashboard/dashboard.html", context)

mrr/dashboard/templates/dashboard/base.html
{% load static %}

{% load crispy_forms_tags %}

<html>
    <head>
        <title>MRR - Dashboard</title>

        <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}">

        <style>
            body{
                background-color: #EEE;
            }
        </style>

        {% block css %}        
        {% endblock css %}
        
        <script src="{% static 'dashboard/js/jquery-3.3.1.slim.min.js' %}"></script>
        <script src="{% static 'dashboard/js/popper.min.js' %}"></script>
        <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
        
        {% block js %}        
        {% endblock js %}

    </head>
    <body>

<nav class="navbar" style="background-color:#879FE6;">
    <a class="navbar-brand" href="#" style="color:#FFF;">MRR - Dashboard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
        {% if form %}
            <div class="navbar-nav">
                <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'dashboard:index' %}">
                        {% csrf_token %}
                        {{form.dt_inicio|as_crispy_field}} {{form.dt_fim|as_crispy_field}}
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Busca</button>
                </form>
            </div>
        {% endif %}
    
</nav>
    <div class="ml-3 mr-3">
        {% block content %}
        {% endblock content %}
    </div>

    </body>
</html>

mrr/dashboard/templates/dashboard/dashboard.html
{% extends "dashboard/base.html" %}

    {% block content %}
        <div class="mt-2">
        <div class="row">
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 col-xl-2">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/mrr.html" as mrr %}
                            {% include mrr %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 col-xl-2">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/new_mrr.html" as new_mrr %}
                            {% include new_mrr %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 col-xl-2">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/expansion_mrr.html" as expansion_mrr %}
                            {% include expansion_mrr %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 col-xl-2">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/ressurected_mrr.html" as ressurected_mrr %}
                            {% include ressurected_mrr %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 col-xl-2">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/contraction_mrr.html" as contraction_mrr %}
                            {% include contraction_mrr %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 col-xl-2">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/canceled_mrr.html" as canceled_mrr %}
                            {% include canceled_mrr %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-1"></div>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/receita_localidade.html" as receita_localidade %}
                            {% include receita_localidade %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-8">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/tendencia_mrr.html" as tendencia_mrr %}
                            {% include tendencia_mrr %}                
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-1"></div>
        <div clas="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                <div class="card">                    
                    <div class="card-body">
                        {% with "dashboard/cli_localidade.html" as cli_localidade %}
                            {% include cli_localidade %}                
                        {% endwith %}                        
                    </div>
                </div>
            </div>
        </div>


    {% endblock content %}
        